"""Rebuild the branding exports from the existing application fonts.

Requires pnpm install and Python: fonttools brotli resvg-py Pillow.
Run from any directory: python design/brand/generate.py
"""
from pathlib import Path
from io import BytesIO
from xml.sax.saxutils import escape
import json
import shutil
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from PIL import Image
from PIL.PngImagePlugin import PngInfo
import resvg_py

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parents[1]
ASSETS = ROOT / 'assets'
ASSETS.mkdir(exist_ok=True)
FONTS = ROOT / 'fonts'
FONTS.mkdir(exist_ok=True)
for family in ('inter', 'jetbrains-mono'):
    source = REPO / 'apps/desktop/node_modules/@fontsource-variable' / family
    shutil.copyfile(source / 'files' / f'{family}-latin-wght-normal.woff2', FONTS / f'{family}-latin-variable.woff2')
    shutil.copyfile(source / 'LICENSE', FONTS / f'{family}-OFL.txt')

fonts = {}
for weight in (400, 500, 600):
    font = TTFont(FONTS / 'inter-latin-variable.woff2')
    fonts[weight] = instantiateVariableFont(font, {'wght': weight}, inplace=True)

def lettering(value, x, y, size, color='#dfe1e5', weight=400, tracking=0):
    font = fonts[weight]
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    scale = size / font['head'].unitsPerEm
    result = []
    cursor = 0
    for character in value:
        glyph = glyphs[cmap[ord(character)]]
        pen = SVGPathPen(glyphs)
        glyph.draw(pen)
        if pen.getCommands():
            result.append(f'<path d="{pen.getCommands()}" transform="translate({cursor},0)"/>')
        cursor += glyph.width + tracking / scale
    return f'<g aria-label="{escape(value)}" fill="{color}" transform="translate({x},{y}) scale({scale},{-scale})">' + ''.join(result) + '</g>'

def mark(color='#ffffff', x=0, y=0, size=64):
    # Approved Option C: Console C. Preserve the selected geometry exactly.
    return f'<g transform="translate({x},{y}) scale({size / 64})" fill="{color}"><path d="M48 16H25L14 27V38L25 49H48V41H29L22 34V31L29 24H48Z"/><rect x="32" y="29" width="18" height="7"/></g>'

def tile(x=0, y=0, size=64):
    return f'<rect x="{x}" y="{y}" width="{size}" height="{size}" rx="{size * .21875}" fill="#7c42ff"/>' + mark(x=x, y=y, size=size)

def svg(width, height, body, title):
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img"><title>{escape(title)}</title>{body}</svg>'

def save(name, width, height, body, title):
    path = ASSETS / f'{name}.svg'
    path.write_text(svg(width, height, body, title), encoding='utf-8')
    return path

def raster(path, width=None):
    rendered = resvg_py.svg_to_bytes(svg_path=str(path), width=width, skip_system_fonts=True)
    metadata = PngInfo()
    metadata.add_text('Description', f'Original cw-code vector branding. Source: design/brand/assets/{path.name}; generated by design/brand/generate.py using bundled Inter/JetBrains Mono fonts. No AI-generated raster imagery.')
    result = BytesIO()
    Image.open(BytesIO(rendered)).save(result, format='PNG', pnginfo=metadata)
    return result.getvalue()

for name, color in [('light', '#dfe1e5'), ('dark', '#101214'), ('white', '#ffffff'), ('violet', '#7c42ff')]:
    save(f'mark-{name}', 64, 64, mark(color), 'cw-code mark')
    save(f'wordmark-{name}', 272, 64, lettering('cw-code', 0, 48, 56, color, 600, -1.1), 'cw-code')
    save(f'lockup-{name}', 352, 64, mark(color) + lettering('cw-code', 80, 48, 56, color, 600, -1.1), 'cw-code')
save('lockup-primary', 352, 64, tile() + lettering('cw-code', 80, 48, 56, weight=600, tracking=-1.1), 'cw-code')
icon = save('app-icon', 64, 64, tile(), 'cw-code application icon')
for size in (16, 20, 22, 24, 32, 40, 48, 64, 128, 256, 512, 1024):
    (ASSETS / f'app-icon-{size}.png').write_bytes(raster(icon, size))
Image.open(BytesIO(raster(icon, 256))).save(ASSETS / 'cw-code.ico', sizes=[(16,16),(24,24),(32,32),(48,48),(64,64),(128,128),(256,256)])
Image.open(BytesIO(raster(icon, 256))).save(ASSETS / 'favicon.ico', sizes=[(16,16),(32,32),(48,48)])
avatar = save('avatar', 512, 512, '<rect width="512" height="512" fill="#7c42ff"/>' + mark(size=512), 'cw-code profile image')
(ASSETS / 'avatar.png').write_bytes(raster(avatar))

for name, width, height in [('social',1200,630), ('repository-social',1280,640)]:
    body = f'<rect width="{width}" height="{height}" fill="#1e1f22"/>'
    body += tile(72,64,64) + lettering('cw-code',156,111,48,weight=600,tracking=-.96)
    body += lettering('Your coding CLIs.',72,280,68,weight=500,tracking=-1.36)
    body += lettering('One desktop workspace.',72,365,68,weight=500,tracking=-1.36)
    body += lettering('Claude Code, OpenCode, and Codex.',72,455,28,'#bcbec4')
    body += lettering('Windows / Open source',72,height-64,20,'#bcbec4')
    path=save(name,width,height,body,'cw-code — Your coding CLIs. One desktop workspace.')
    (ASSETS / f'{name}.png').write_bytes(raster(path))

body='<rect width="1440" height="1680" fill="#1e1f22"/>'
body+=tile(72,64,64)+lettering('cw-code',156,111,48,weight=600,tracking=-.96)
body+=lettering('Brand identity',1050,102,24,'#bcbec4')
body+=lettering('Your coding CLIs.',72,270,88,weight=500,tracking=-1.76)
body+=lettering('One desktop workspace.',72,377,88,weight=500,tracking=-1.76)
body+=lettering('A desktop workspace for Claude Code, OpenCode, and Codex.',76,451,28,'#bcbec4')
body+='<rect x="72" y="518" width="840" height="326" rx="12" fill="#101214"/>'
body+=mark(x=116,y=578,size=192)+lettering('cw-code',350,713,112,weight=600,tracking=-2.24)
body+='<rect x="936" y="518" width="432" height="326" rx="12" fill="#dfe1e5"/>'
body+=mark('#101214',984,560,140)+lettering('cw-code',983,777,68,'#101214',600,-1.36)
body+=lettering('Console C / horizontal lockup',72,887,20,'#bcbec4')
body+=lettering('One-color reproduction',936,887,20,'#bcbec4')
body+=lettering('Inter',72,1000,44,weight=600)+lettering('JetBrains Mono',750,1000,44,weight=500)
body+=lettering('Clear headings. Direct language.',72,1047,24,'#bcbec4')
body+=lettering('Code, paths, commands, output.',750,1047,24,'#bcbec4')
# Font specimen itself uses the actual bundled mono face, outlined independently.
mono=TTFont(FONTS/'jetbrains-mono-latin-variable.woff2')
fonts[700]=instantiateVariableFont(mono,{'wght':400},inplace=True)
body+=lettering('Aa Bb Cc 0123456789',72,1111,34)
body+=lettering('git diff --stat',750,1111,30,weight=700)
palette=[('Graphite','#1e1f22'),('Editor','#101214'),('Raised','#2e3035'),('Text','#dfe1e5'),('Violet','#7c42ff'),('Focus','#548af7')]
for index,(name,color) in enumerate(palette):
    x=72+index*220
    body+=f'<rect x="{x}" y="1190" width="196" height="76" rx="6" fill="{color}" stroke="#393b40"/>'
    body+=lettering(name,x,1302,20)+lettering(color,x,1332,18,'#bcbec4')
body+=lettering('App icon',72,1442,24,weight=600)
for x,size in [(72,16),(126,22),(186,32),(258,48),(346,64),(450,96)]:
    body+=tile(x,1470,size)+lettering(str(size),x,1608,16,'#bcbec4')
body+=lettering('Run sessions across projects.',750,1466,28,weight=500)
body+=lettering('Inspect files and diffs. Open a terminal.',750,1510,28,weight=500)
body+=lettering('Uses your installed CLIs and their authentication.',750,1578,20,'#bcbec4')
board=save('brand-sheet',1440,1680,body,'cw-code brand identity: logo, typography, palette and app icons')
(ROOT / 'brand-sheet.png').write_bytes(raster(board))

tokens={'name':'cw-code','logo':{'direction':'C','name':'Console C','primaryTreatment':'violet','status':'selected'},'colors':dict((name.lower(),color) for name,color in palette),'typography':{'sans':'Inter Variable','mono':'JetBrains Mono Variable','wordmark':{'weight':600,'trackingEm':-.02}},'source':'apps/desktop/src/renderer/src/theme.css','status':'Console C integrated into desktop and README; installer release pending'}
(ROOT/'tokens.json').write_text(json.dumps(tokens,indent=2)+'\n',encoding='utf-8')
print(f'Generated {len(list(ASSETS.iterdir()))} assets and brand-sheet.png')

# Keep runtime and packaging assets synchronized with the canonical brand export.
renderer_assets = REPO / 'apps/desktop/src/renderer/src/assets'
resources = REPO / 'apps/desktop/resources'
renderer_assets.mkdir(exist_ok=True)
resources.mkdir(exist_ok=True)
shutil.copyfile(ASSETS / 'app-icon.svg', renderer_assets / 'console-c.svg')
shutil.copyfile(ASSETS / 'cw-code.ico', resources / 'icon.ico')
for notice in ('inter-OFL.txt', 'jetbrains-mono-OFL.txt'):
    shutil.copyfile(FONTS / notice, resources / notice)
shutil.copyfile(REPO / 'LICENSE', resources / 'LICENSE.txt')
